services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: Test-Unitaire_Esiee
    ports:
      - "3000:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:UnitTestEsieeDb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update