enum CategorieObjet {
    MOBILIER = 'MOBILIER',
    JARDINAGE = 'JARDINAGE',
    INFORMATIQUE = 'INFORMATIQUE',
    GAMING = 'GAMING',
    OUTILS = 'OUTILS',
    COLLECTION = 'COLLECTION',
    LITTERATURE = 'LITTERATURE',
    VETEMENTS = 'VETEMENTS',
    ELECTROMENAGER = 'ELECTROMENAGER',
    AUTRE = 'AUTRE'
}

export default CategorieObjet;